apiVersion: v1
kind: Service
metadata:
  name: {{ include "bluegreen.fullname" . }}
  labels:
    {{- include "bluegreen.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "bluegreen.fullname" . }}-preview
  labels:
    {{- include "bluegreen.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080
