apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argo-rollouts-demo
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Argo Rollouts demo applications
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
status: {}
