apiVersion: v1
kind: Service
metadata:
  name: {{ include "rolling.fullname" . }}
  labels:
    {{- include "rolling.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080
